version: '5'

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db

  twitterapp:
    image: twitterapp
    ports:
      - 8080:8080
    links:
      - mongodb
volumes:
  mongodata: