version: '5'

services:
  mongodb:
    image: "mongo:latest"
    container_name: "mongodb"
    ports:
      - 27018:27017
    volumes:
      - mongodata:/data/db

  mongo-init:
    image: mongo:latest
    restart: "no"
    depends_on:
      mongodb:
        condition: service_healthy
    command: >
      mongo --host mongodb:27017 --eval
      '
      rs.initiate( {
         _id : "rs0",
         members: [
            { _id: 0, host: "localhost:27017" }
         ]
      })
      '

  twitterapp:
    image: twitterapp
    ports:
      - 8080:8080
    links:
      - mongodb
volumes:
  mongodata: